import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useMemo, useRef, useState } from "react";
import { Activity, BarChart3, Check, Copy, Crosshair, Download, Gauge, Languages, LogOut, Save, ShieldCheck, SlidersHorizontal, Smartphone, Sparkles, Target, Trash2, Volume2, VolumeX, Zap } from "lucide-react";
import { AdminPanel } from "@/components/sensix/AdminPanel";
import { KeyGate } from "@/components/sensix/KeyGate";
import { PullSimulator, type SimResult } from "@/components/sensix/PullSimulator";
import { checkSession, deleteProfile, listProfiles, saveProfile } from "@/lib/keys.functions";
import { BRANDS, CPU_TIERS, RESOLUTIONS, compute, idealDpi, type EngineInput, type Mode, type Preference, type PullStyle } from "@/lib/sensi-engine";
import { loadSession, storeSession, timeLeft, type Session } from "@/lib/session";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "SensiX Pro — Otimização de Mira Free Fire" },
    { name: "description", content: "Motor avançado de sensibilidade, recoil, DPI e treino de puxada para Free Fire." },
    { property: "og:title", content: "SensiX Pro — Otimização de Mira Free Fire" },
    { property: "og:description", content: "Calibre sua sensibilidade, botão de tiro, DPI e estabilidade com precisão." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ] }), component: Index,
});

type Profile = { id: string; name: string; data: Record<string, string | number | boolean | null>; created_at: string };
const initial: EngineInput = { mode:"br", preference:"mid", brandId:"samsung", dpi:411, resW:1080, resH:2400, fireButton:50, pull:"linear", inputLag:2, touchDelay:80, dragFactor:1 };
const labels = { pt:{ hero:"CENTRAL DE MIRA", sub:"Engenharia de precisão para dominar o arraste, neutralizar o recoil e encontrar sua configuração competitiva.", config:"CONFIGURAÇÃO DE COMBATE", result:"CONFIGURAÇÃO SUPREMA", sim:"SIMULADOR DRAG & RECOIL", stability:"ANTI-TREMEDEIRA & ESTABILIDADE", profiles:"PERFIS DE ATLETA", dpi:"DPI IDEAL POR HARDWARE" }, en:{ hero:"AIM COMMAND CENTER", sub:"Precision engineering to master drag, neutralize recoil and find your competitive setup.", config:"COMBAT CONFIGURATION", result:"SUPREME CONFIGURATION", sim:"DRAG & RECOIL SIMULATOR", stability:"ANTI-SHAKE & STABILITY", profiles:"ATHLETE PROFILES", dpi:"IDEAL DPI BY HARDWARE" } };

function Index(){
 const check=useServerFn(checkSession); const [session,setSession]=useState<Session|null>(null); const [ready,setReady]=useState(false);
 useEffect(()=>{ const saved=loadSession(); if(!saved){setReady(true);return} void check({data:{token:saved.token}}).then(r=>{if(r.ok){const next={...saved,role:r.role,expiresAt:r.expiresAt,duration:r.duration};storeSession(next);setSession(next)}else storeSession(null)}).finally(()=>setReady(true)); },[]);
 if(!ready) return <div className="app-shell boot"><Activity className="spin"/><b>INITIALIZING SENSIX CORE</b></div>;
 if(!session) return <KeyGate onLogin={s=>{storeSession(s);setSession(s)}}/>;
 const logout=()=>{storeSession(null);setSession(null)};
 return <div className="app-shell"><div className="hud-grid"/><header className="topbar"><div className="brand"><span className="brand-mark"><Crosshair/></span><div><strong>SENSI<span>X</span> PRO</strong><small>FREE FIRE PERFORMANCE OS</small></div></div><div className="system-status"><span className="status-dot"/><div><b>OPERATIONAL</b><small>{session.role==="admin"?"ADMIN COMMAND":"ANTI-LAG ENGINE READY"}</small></div></div><div className="header-actions"><span className="access-time">{session.role==="admin"?"ADMIN":timeLeft(session.expiresAt)}</span><button className="icon-action" onClick={logout} aria-label="Sair"><LogOut/></button></div></header>{session.role==="admin"?<AdminPanel token={session.token}/>:<Dashboard session={session}/>}</div>;
}

function Dashboard({session}:{session:Session}){
 const saveFn=useServerFn(saveProfile), listFn=useServerFn(listProfiles), deleteFn=useServerFn(deleteProfile);
 const [lang,setLang]=useState<"pt"|"en">("pt"), [sound,setSound]=useState(true), [input,setInput]=useState<EngineInput>(initial), [sim,setSim]=useState<SimResult|null>(null), [profiles,setProfiles]=useState<Profile[]>([]), [profileName,setProfileName]=useState("Minha build"), [toast,setToast]=useState(""); const [cpu,setCpu]=useState("sd7"), [gyro,setGyro]=useState(45), [friction,setFriction]=useState(35), [stabilizer,setStabilizer]=useState(60); const audio=useRef<AudioContext|null>(null); const t=labels[lang];
 const output=useMemo(()=>compute({...input,dragFactor:sim?.factor??1,fireButton:sim?.fire??input.fireButton}),[input,sim]); const dpiRec=idealDpi(cpu,input.resW);
 const buzz=(kind:"tap"|"generate"="tap")=>{if(navigator.vibrate)navigator.vibrate(kind==="generate"?[25,35,45]:12);if(!sound)return;const C=window.AudioContext||(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!C)return;const c=audio.current??new C();audio.current=c;const o=c.createOscillator(),g=c.createGain();o.frequency.value=kind==="generate"?170:560;g.gain.value=.035;o.connect(g).connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.09);o.stop(c.currentTime+.1)};
 const note=(s:string)=>{setToast(s);window.setTimeout(()=>setToast(""),2500)}; const loadProfiles=async()=>{try{setProfiles(await listFn({data:{token:session.token}}) as Profile[])}catch{note("Falha ao carregar perfis")}}; useEffect(()=>{void loadProfiles()},[]);
 const copy=async()=>{await navigator.clipboard.writeText(Object.entries(output).filter(([,v])=>typeof v==="number").map(([k,v])=>`${k}: ${v}${k==="fireButton"?"%":""}`).join("\n"));buzz();note("Configuração copiada")};
 const save=async()=>{try{await saveFn({data:{token:session.token,name:profileName,data:{...input,dragFactor:sim?.factor??1,...output}}});await loadProfiles();note("Perfil salvo na nuvem")}catch{note("Não foi possível salvar")}};
 const apply=(p:Profile)=>{setInput({...initial,mode:String(p.data.mode??"br") as Mode,preference:String(p.data.preference??"mid") as Preference,brandId:String(p.data.brandId??"samsung"),dpi:Number(p.data.dpi??411),resW:Number(p.data.resW??1080),resH:Number(p.data.resH??2400),fireButton:Number(p.data.fireButton??50),pull:String(p.data.pull??"linear") as PullStyle,inputLag:Number(p.data.inputLag??2),touchDelay:Number(p.data.touchDelay??80),dragFactor:Number(p.data.dragFactor??1)});setSim(null);note("Perfil aplicado")};
 const exportCard=()=>{const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="675"><rect width="1200" height="675" fill="#08090d"/><text x="70" y="95" fill="#ff6500" font-size="30" font-family="sans-serif" font-weight="700">SENSIX PRO // ATHLETE CARD</text><text x="70" y="160" fill="#9cecff" font-size="22" font-family="sans-serif">${profileName.replace(/[<>&]/g,"")}</text>${Object.entries({GERAL:output.geral,"RED DOT":output.redDot,ACOG:output.acog,"4X":output.x4,AWM:output.awm,"CÂMERA":output.camera,"BOTÃO":output.fireButton+"%"}).map(([k,v],i)=>`<text x="${70+(i%4)*270}" y="${270+Math.floor(i/4)*170}" fill="#f4f7fb" font-size="28" font-family="sans-serif">${k}</text><text x="${70+(i%4)*270}" y="${335+Math.floor(i/4)*170}" fill="#a6f1ff" font-size="62" font-family="sans-serif" font-weight="700">${v}</text>`).join("")}<text x="70" y="625" fill="#6e7584" font-size="18" font-family="sans-serif">${BRANDS.find(b=>b.id===input.brandId)?.label} • ${input.dpi} DPI • ${input.resW}×${input.resH}</text></svg>`;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([svg],{type:"image/svg+xml"}));a.download="sensix-athlete-card.svg";a.click();URL.revokeObjectURL(a.href);note("Card de atleta exportado")};
 const set=<K extends keyof EngineInput>(k:K,v:EngineInput[K])=>setInput(x=>({...x,[k]:v}));
 return <main className="sx-page">
  <section className="sx-hero"><div><p className="eyebrow"><span/> SENSIX CORE 3.0 // LIVE CALIBRATION</p><h1>{t.hero.split(" ").slice(0,-1).join(" ")} <em>{t.hero.split(" ").at(-1)}</em></h1><p>{t.sub}</p><div className="hero-actions"><button className="ui-button" onClick={()=>document.getElementById("engine")?.scrollIntoView()}><Target/> INICIAR CALIBRAÇÃO</button><button className="ui-button ui-button-outline" onClick={exportCard}><Download/> CARD DE ATLETA</button></div></div><div className="hero-scope"><span>REAL-TIME AIM MATRIX</span><Crosshair/><b>{output.geral}</b><small>GERAL / 200</small></div></section>
  <nav className="quick-nav">{[["01",t.config,"engine"],["02",t.sim,"sim"],["03",t.stability,"stability"],["04",t.profiles,"profiles"]].map(([n,l,id])=><button key={id} onClick={()=>document.getElementById(id)?.scrollIntoView()}><span>{n}</span><Target size={14}/><b>{l}</b></button>)}</nav>
  <div className="top-tools"><button className="ui-button ui-button-ghost" onClick={()=>setLang(lang==="pt"?"en":"pt")}><Languages/> {lang.toUpperCase()}</button><button className="icon-action" onClick={()=>setSound(!sound)} aria-label="Som">{sound?<Volume2/>:<VolumeX/>}</button></div>
  <section id="engine" className="panel"><Title icon={<SlidersHorizontal/>} tag="CORE // WEIGHTED ENGINE" title={t.config}/><div className="sx-form-grid">
   <label>Modo de jogo<select value={input.mode} onChange={e=>set("mode",e.target.value as Mode)}><option value="br">Battle Royale Rankeado</option><option value="cs">Apostado / 4v4</option><option value="x1">X1 / 1v1</option></select></label><label>Preferência de puxada<select value={input.preference} onChange={e=>set("preference",e.target.value as Preference)}><option value="low">Baixa / precisa</option><option value="mid">Mediana / versátil</option><option value="high">Alta / veloz</option></select></label><label>Marca / família<select value={input.brandId} onChange={e=>set("brandId",e.target.value)}>{BRANDS.map(b=><option key={b.id} value={b.id}>{b.label}</option>)}</select></label><label>DPI atual<input className="sx-input" type="number" min="360" max="960" value={input.dpi} onChange={e=>set("dpi",Math.max(360,Math.min(960,+e.target.value)))}/></label><label>Resolução<select value={`${input.resW}x${input.resH}`} onChange={e=>{const [w,h]=e.target.value.split("x").map(Number);setInput(x=>({...x,resW:w||1080,resH:h||2400}))}}>{RESOLUTIONS.map(r=><option key={r.id} value={`${r.w}x${r.h}`}>{r.label}</option>)}<option value={`${input.resW}x${input.resH}`}>Personalizada</option></select></label><label>Fire button <b>{input.fireButton}%</b><input type="range" min="30" max="80" value={input.fireButton} onChange={e=>set("fireButton",+e.target.value)}/></label><label>Estilo mecânico<select value={input.pull} onChange={e=>set("pull",e.target.value as PullStyle)}><option value="linear">Linear</option><option value="short">Curta</option><option value="explosive">Explosiva</option></select></label><label>Input lag percebido <b>{input.inputLag}/10</b><input type="range" min="0" max="10" value={input.inputLag} onChange={e=>set("inputLag",+e.target.value)}/></label><label>Atraso de toque <b>{input.touchDelay} ms</b><input type="range" min="0" max="200" step="5" value={input.touchDelay} onChange={e=>set("touchDelay",+e.target.value)}/></label><label>Largura personalizada<input className="sx-input" type="number" min="480" max="2160" value={input.resW} onChange={e=>set("resW",+e.target.value)}/></label><label>Altura personalizada<input className="sx-input" type="number" min="800" max="3840" value={input.resH} onChange={e=>set("resH",+e.target.value)}/></label>
  </div></section>
  <section className="result-panel"><div className="result-head"><div><p>OUTPUT // LIVE</p><h2>{t.result}</h2></div><div className="result-actions"><button className="ui-button ui-button-outline" onClick={copy}><Copy/> COPIAR</button><button className="ui-button" onClick={()=>{setInput(x=>({...x,dpi:Math.max(360,Math.min(960,x.dpi+[17,-13,9][Math.floor(Math.random()*3)]))}));buzz("generate");note("Nova combinação calculada")}}><Sparkles/> NOVA COMBINAÇÃO</button></div></div><div className="sensi-output">{[["GERAL",output.geral],["RED DOT",output.redDot],["ACOG / 2X",output.acog],["MIRA 4X",output.x4],["AWM",output.awm],["CÂMERA",output.camera]].map(([k,v])=><div className="sensi-stat" key={k}><span>{k}</span><strong>{v}</strong><div><i style={{width:`${Number(v)/2}%`}}/></div></div>)}</div><div className="factor-strip">{output.factors.map(f=><span key={f.label}>{f.label}<b>{f.value}</b></span>)}<span>BOTÃO IDEAL<b>{output.fireButton}%</b></span></div></section>
  <section id="sim" className="panel"><Title icon={<Target/>} tag="PHYSICS // POINTER INPUT" title={t.sim} text="Segure o botão e arraste até a zona vermelha. Velocidade, trajetória e tremor recalibram o motor."/><PullSimulator baseFire={output.fireButton} onResult={setSim} buzz={buzz}/></section>
  <div className="two-column"><section id="stability" className="panel"><Title icon={<Activity/>} tag="RECOIL // CONTROL" title={t.stability}/><div className="slider-stack">{[["Giroscópio",gyro,setGyro],["Fricção da tela",friction,setFriction],["Estabilização de toque",stabilizer,setStabilizer]].map(([n,v,fn])=><label key={String(n)}><span>{n}<output>{String(v)}%</output></span><input type="range" min="0" max="100" value={Number(v)} onChange={e=>(fn as (v:number)=>void)(+e.target.value)}/></label>)}</div><div className="recoil-readout"><svg viewBox="0 0 260 100"><path d={`M130 92 C ${125+(50-friction)/3} 75, ${150+(50-stabilizer)/2} 58, ${120+(50-gyro)/2} 8`} /><line x1="130" y1="95" x2="130" y2="5"/></svg><p><b>{stabilizer>65?"MATRIZ ESTÁVEL":stabilizer>35?"CONTROLE EQUILIBRADO":"TREINO RECOMENDADO"}</b><span>{input.pull==="explosive"?"Faça 3 séries de 15 puxadas curtas, priorizando parada na cabeça.":"Treine parede por 5 minutos mantendo a linha vertical e soltando o toque no alvo."}</span></p></div></section>
   <section className="panel"><Title icon={<Gauge/>} tag="HARDWARE // TOUCH SAMPLING" title={t.dpi}/><label>Processador<select value={cpu} onChange={e=>setCpu(e.target.value)}>{CPU_TIERS.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><div className="dpi-result"><Smartphone/><div><small>FAIXA SEGURA RECOMENDADA</small><strong>{dpiRec.text}</strong><span>Touch sampling de referência: {dpiRec.hz}</span></div></div><p className="tech-note">A recomendação cruza resolução e classe de hardware para reduzir travamentos e perda de registro. Não altera seu aparelho automaticamente.</p></section></div>
  <section id="profiles" className="panel"><Title icon={<BarChart3/>} tag="CLOUD // COMPARE" title={t.profiles} text="Salve até 50 testes e volte à configuração que melhor performou."/><div className="profile-create"><input className="sx-input" maxLength={60} value={profileName} onChange={e=>setProfileName(e.target.value)} aria-label="Nome do perfil"/><button className="ui-button" onClick={save}><Save/> SALVAR TESTE</button><button className="ui-button ui-button-outline" onClick={exportCard}><Download/> EXPORTAR CARD</button></div><div className="profile-grid">{profiles.length===0?<p className="empty-state">Nenhum teste salvo. Calibre e salve sua primeira build.</p>:profiles.map(p=><article className="profile-card" key={p.id}><div><small>{new Date(p.created_at).toLocaleDateString("pt-BR")}</small><h3>{p.name}</h3></div><div className="profile-numbers"><span>GERAL <b>{p.data.geral??"—"}</b></span><span>RED DOT <b>{p.data.redDot??"—"}</b></span><span>BOTÃO <b>{p.data.fireButton??"—"}%</b></span></div><div className="profile-actions"><button onClick={()=>apply(p)}>APLICAR</button><button aria-label="Excluir perfil" onClick={async()=>{await deleteFn({data:{token:session.token,id:p.id}});await loadProfiles()}}><Trash2/></button></div></article>)}</div></section>
  <section className="pro-tips"><div><p>PROTOCOL // COACH</p><h2>ROTINAS DINÂMICAS</h2></div>{[{n:"01",h:"Parede antes do ranked",p:"Faça 30 puxadas usando apenas Geral e Red Dot. Ajuste no máximo 4 pontos por rodada."},{n:"02",h:"Controle o overflick",p:"Se a mira ultrapassa a cabeça, aumente o botão e reduza a sensibilidade em pequenos passos."},{n:"03",h:"Priorize FPS estável",p:"Sombras desligadas e FPS alto melhoram consistência mais que elevar DPI além da faixa segura."}].map(x=><article key={x.n}><b>{x.n}</b><h3>{x.h}</h3><p>{x.p}</p></article>)}</section>
  <footer><div className="brand-mini"><Crosshair/> SENSIX PRO</div><p>FERRAMENTA DE CALIBRAÇÃO — RESULTADOS VARIAM POR APARELHO E MECÂNICA</p><ShieldCheck/></footer>{toast&&<div className="toast"><Check/>{toast}</div>}
 </main>;
}
function Title({icon,tag,title,text}:{icon:React.ReactNode;tag:string;title:string;text?:string}){return <div className="section-title"><span className="section-icon">{icon}</span><div><p className="section-tag">{tag}</p><h2>{title}</h2>{text&&<p>{text}</p>}</div></div>}
