import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useMemo, useRef, useState } from "react";
import { Activity, BarChart3, Check, Copy, Crosshair, Download, Gauge, Languages, LogOut, MonitorCog, Save, ShieldCheck, SlidersHorizontal, Smartphone, Target, Trash2, Volume2, VolumeX, Zap } from "lucide-react";
import { AdminPanel } from "@/components/sensix/AdminPanel";
import { AimLab, type TrainingResult } from "@/components/sensix/AimLab";
import { KeyGate } from "@/components/sensix/KeyGate";
import { checkSession, deleteProfile, listProfiles, saveProfile } from "@/lib/keys.functions";
import { BRANDS, CPU_TIERS, RESOLUTIONS, compute, idealDpi, idealResolution, type EngineInput, type Mode, type Preference, type PullStyle } from "@/lib/sensi-engine";
import { loadSession, storeSession, timeLeft, type Session } from "@/lib/session";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Free Fire Aim Lab & Hyper-Sensitivity Engine" },
    { name: "description", content: "Laboratório de mira jogável com treino UMP, aim assist, sensibilidade, DPI e análise de puxada para Free Fire." },
    { property: "og:title", content: "Free Fire Aim Lab & Hyper-Sensitivity Engine" },
    { property: "og:description", content: "Treine a puxada de capa e calibre sensibilidade, DPI, FPS e botão de tiro com telemetria em tempo real." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ] }), component: Index,
});

type Profile = { id:string; name:string; data:Record<string,string|number|boolean|null>; created_at:string };
const initial: EngineInput = { mode:"br", preference:"mid", brandId:"samsung", dpi:411, resW:1080, resH:2400, fireButton:50, pull:"linear", inputLag:2, touchDelay:80, fps:60, pointerSpeed:5, dragFactor:1 };
const FPS = [30,45,60,90,120,144,240] as const;

function Index(){
  const check=useServerFn(checkSession); const [session,setSession]=useState<Session|null>(null); const [ready,setReady]=useState(false);
  useEffect(()=>{const saved=loadSession();if(!saved){setReady(true);return}void check({data:{token:saved.token}}).then(r=>{if(r.ok){const next={...saved,role:r.role,expiresAt:r.expiresAt,duration:r.duration};storeSession(next);setSession(next)}else storeSession(null)}).finally(()=>setReady(true))},[]);
  if(!ready)return <div className="app-shell boot"><Activity className="spin"/><b>BOOTING AIM LAB CORE</b></div>;
  if(!session)return <KeyGate onLogin={s=>{storeSession(s);setSession(s)}}/>;
  return <div className="app-shell"><div className="hud-grid"/><Header session={session} logout={()=>{storeSession(null);setSession(null)}}/>{session.role==="admin"?<AdminPanel token={session.token}/>:<Dashboard session={session}/>}</div>;
}

function Header({session,logout}:{session:Session;logout:()=>void}){return <header className="topbar"><div className="brand"><span className="brand-mark"><Crosshair/></span><div><strong>AIM LAB <span>// HX</span></strong><small>HYPER-SENSITIVITY ENGINE</small></div></div><div className="system-status"><span className="status-dot"/><div><b>ENGINE ONLINE</b><small>UMP BALLISTICS // READY</small></div></div><div className="header-actions"><span className="access-time">{session.role==="admin"?"ADMIN":timeLeft(session.expiresAt)}</span><button className="icon-action" onClick={logout} aria-label="Sair"><LogOut/></button></div></header>}

function Dashboard({session}:{session:Session}){
  const saveFn=useServerFn(saveProfile),listFn=useServerFn(listProfiles),deleteFn=useServerFn(deleteProfile);
  const [lang,setLang]=useState<"pt"|"en">("pt"),[sound,setSound]=useState(true),[input,setInput]=useState<EngineInput>(initial),[training,setTraining]=useState<TrainingResult|null>(null),[profiles,setProfiles]=useState<Profile[]>([]),[profileName,setProfileName]=useState("Build Aim Lab"),[toast,setToast]=useState(""),[cpu,setCpu]=useState("sd7");
  const pageRef=useRef<HTMLElement>(null); const output=useMemo(()=>compute({...input,dragFactor:training?.factor??1,fireButton:training?.fireButton??input.fireButton}),[input,training]); const dpiRec=idealDpi(cpu,input.resW); const resolutionRec=idealResolution(cpu,input.fps);
  const set=<K extends keyof EngineInput>(key:K,value:EngineInput[K])=>setInput(current=>({...current,[key]:value}));
  const note=(text:string)=>{setToast(text);window.setTimeout(()=>setToast(""),2400)};
  const loadProfiles=async()=>{try{setProfiles(await listFn({data:{token:session.token}}) as Profile[])}catch{note("Falha ao carregar perfis")}};
  useEffect(()=>{void loadProfiles()},[]);
  useEffect(()=>{const root=pageRef.current;if(!root)return;const reveal=new IntersectionObserver(entries=>entries.forEach(entry=>entry.target.classList.toggle("is-visible",entry.isIntersecting)),{threshold:.12});root.querySelectorAll(".reveal").forEach(el=>reveal.observe(el));const tilt=(event:PointerEvent)=>{const target=(event.target as HTMLElement).closest<HTMLElement>(".reactive-panel");if(!target)return;const r=target.getBoundingClientRect(),x=(event.clientX-r.left)/r.width,y=(event.clientY-r.top)/r.height;target.style.setProperty("--mx",`${x*100}%`);target.style.setProperty("--my",`${y*100}%`);target.style.setProperty("--rx",`${(0.5-y)*2.2}deg`);target.style.setProperty("--ry",`${(x-0.5)*2.2}deg`)};root.addEventListener("pointermove",tilt);return()=>{reveal.disconnect();root.removeEventListener("pointermove",tilt)}},[]);
  const copy=async()=>{await navigator.clipboard.writeText(`Geral ${output.geral}\nRed Dot ${output.redDot}\n2X ${output.acog}\n4X ${output.x4}\nAWM ${output.awm}\nCâmera ${output.camera}\nBotão ${output.fireButton}%`);note("Configuração copiada")};
  const save=async()=>{try{await saveFn({data:{token:session.token,name:profileName,data:{...input,trainingFactor:training?.factor??1,...output}}});await loadProfiles();note("Build salva") }catch{note("Não foi possível salvar")}};
  const apply=(p:Profile)=>{setInput({...initial,mode:String(p.data.mode??"br") as Mode,preference:String(p.data.preference??"mid") as Preference,brandId:String(p.data.brandId??"samsung"),dpi:Number(p.data.dpi??411),resW:Number(p.data.resW??1080),resH:Number(p.data.resH??2400),fireButton:Number(p.data.fireButton??50),pull:String(p.data.pull??"linear") as PullStyle,inputLag:Number(p.data.inputLag??2),touchDelay:Number(p.data.touchDelay??80),fps:Number(p.data.fps??60) as EngineInput["fps"],pointerSpeed:Number(p.data.pointerSpeed??5),dragFactor:Number(p.data.dragFactor??1)});setTraining(null);note("Build aplicada")};
  const exportCard=()=>{const safe=profileName.replace(/[<>&]/g,"");const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="675"><rect width="1200" height="675" fill="#07090b"/><text x="65" y="82" fill="#efc84a" font-size="24" font-family="sans-serif">FREE FIRE AIM LAB // ATHLETE BUILD</text><text x="65" y="137" fill="#edf8fa" font-size="38" font-family="sans-serif" font-weight="700">${safe}</text>${Object.entries({GERAL:output.geral,"RED DOT":output.redDot,"2X":output.acog,"4X":output.x4,AWM:output.awm,BOTÃO:output.fireButton+"%"}).map(([k,v],i)=>`<text x="${65+(i%3)*365}" y="${250+Math.floor(i/3)*180}" fill="#789096" font-size="18" font-family="sans-serif">${k}</text><text x="${65+(i%3)*365}" y="${325+Math.floor(i/3)*180}" fill="#f2fbfc" font-size="66" font-family="sans-serif" font-weight="700">${v}</text>`).join("")}<text x="65" y="625" fill="#789096" font-size="18" font-family="sans-serif">${input.dpi} DPI · ${input.fps} FPS · ${input.resW}×${input.resH}</text></svg>`;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([svg],{type:"image/svg+xml"}));a.download="aim-lab-athlete-build.svg";a.click();URL.revokeObjectURL(a.href);note("Card exportado")};
  return <main ref={pageRef} className={`sx-page aim-page theme-${input.preference}`} data-motion={input.preference}>
    <section className="aim-hero reveal"><div className="hero-copy"><p className="eyebrow"><span/> FREE FIRE PERFORMANCE LAB // 04.7</p><h1>DOMINE O <em>PRIMEIRO TIRO.</em></h1><p>Treino balístico, leitura de hardware e sensibilidade adaptativa em uma única central competitiva.</p><div className="hero-actions"><button className="ui-button" onClick={()=>document.getElementById("lab")?.scrollIntoView()}><Target/> ENTRAR NA ARENA</button><button className="ui-button ui-button-outline" onClick={()=>document.getElementById("engine")?.scrollIntoView()}><SlidersHorizontal/> CALIBRAR HARDWARE</button></div></div><div className="hero-telemetry reactive-panel"><div className="scope-orbit"><Crosshair/><strong>{output.geral}</strong><small>GERAL / 200</small></div><div><span>AXIS X <b>{output.axisX}</b></span><span>AXIS Y <b>{output.axisY}</b></span><span>LATENCY <b>{Math.round(1000/input.fps+input.touchDelay)}ms</b></span></div></div></section>
    <nav className="command-nav"><button onClick={()=>document.getElementById("lab")?.scrollIntoView()}><b>01</b><span>ARENA UMP</span></button><button onClick={()=>document.getElementById("engine")?.scrollIntoView()}><b>02</b><span>HYPER ENGINE</span></button><button onClick={()=>document.getElementById("analysis")?.scrollIntoView()}><b>03</b><span>DIAGNÓSTICO</span></button><button onClick={()=>document.getElementById("profiles")?.scrollIntoView()}><b>04</b><span>BUILDS</span></button><div className="nav-tools"><button onClick={()=>setLang(lang==="pt"?"en":"pt")} aria-label="Idioma"><Languages/></button><button onClick={()=>setSound(!sound)} aria-label="Som">{sound?<Volume2/>:<VolumeX/>}</button></div></nav>
    <section id="lab" className="panel lab-panel reactive-panel reveal"><SectionTitle icon={<Target/>} kicker="PLAYABLE RANGE // UMP" title="SIMULADOR DE PUXADA DE CAPA" text="Segure em qualquer ponto da arena e arraste para cima. A mira vermelha indica o magnetismo no torso."/><AimLab sound={sound} baseFire={output.fireButton} onResult={setTraining}/></section>
    <section id="engine" className="panel reactive-panel reveal"><SectionTitle icon={<MonitorCog/>} kicker="BIDIRECTIONAL CORE // LIVE" title="HYPER-SENSITIVITY ENGINE" text="Cada variável altera a escala dos eixos, latência percebida e recomendação final."/><div className="preference-switch"><button className={input.preference==="low"?"active":""} onClick={()=>set("preference","low")}><i/>BAIXA <small>CIRÚRGICA</small></button><button className={input.preference==="mid"?"active":""} onClick={()=>set("preference","mid")}><i/>MÉDIA <small>VERSÁTIL</small></button><button className={input.preference==="high"?"active":""} onClick={()=>set("preference","high")}><i/>ALTA <small>BRUTAL</small></button></div><div className="sx-form-grid">
      <Field label="MODO"><select value={input.mode} onChange={e=>set("mode",e.target.value as Mode)}><option value="br">BR Rankeado</option><option value="cs">Apostado / 4v4</option><option value="x1">X1 / 1v1</option></select></Field><Field label="MARCA / MODELO"><select value={input.brandId} onChange={e=>set("brandId",e.target.value)}>{BRANDS.map(b=><option key={b.id} value={b.id}>{b.label}</option>)}</select></Field><Field label="MECÂNICA"><select value={input.pull} onChange={e=>set("pull",e.target.value as PullStyle)}><option value="linear">Linear</option><option value="short">Curta</option><option value="explosive">Explosiva</option></select></Field><Field label="RESOLUÇÃO"><select value={`${input.resW}x${input.resH}`} onChange={e=>{const [w,h]=e.target.value.split("x").map(Number);setInput(x=>({...x,resW:w||1080,resH:h||2400}))}}>{RESOLUTIONS.map(r=><option key={r.id} value={`${r.w}x${r.h}`}>{r.label}</option>)}</select></Field><Field label="DPI ATUAL"><input className="sx-input" type="number" min="120" max="1200" value={input.dpi} onChange={e=>set("dpi",Math.max(120,Math.min(1200,+e.target.value||120)))}/></Field><Field label="FPS"><select value={input.fps} onChange={e=>set("fps",Number(e.target.value) as EngineInput["fps"])}>{FPS.map(f=><option key={f} value={f}>{f} FPS</option>)}</select></Field><Range label="BOTÃO DE ATIRAR" value={training?.fireButton??input.fireButton} min={10} max={100} unit="%" onChange={v=>{set("fireButton",v);setTraining(null)}}/><Range label="VELOCIDADE DO PONTEIRO" value={input.pointerSpeed} min={1} max={10} unit="/10" onChange={v=>set("pointerSpeed",v)}/><Range label="INPUT LAG PERCEBIDO" value={input.inputLag} min={0} max={10} unit="/10" onChange={v=>set("inputLag",v)}/><Range label="ATRASO DE TOQUE" value={input.touchDelay} min={0} max={200} step={5} unit="ms" onChange={v=>set("touchDelay",v)}/>
    </div></section>
    <section id="analysis" className="result-panel reactive-panel reveal"><div className="result-head"><div><p>OUTPUT // TRAINING-SYNCED</p><h2>CONFIGURAÇÃO DE COMBATE</h2></div><div className="result-actions"><button className="ui-button ui-button-outline" onClick={copy}><Copy/> COPIAR</button><button className="ui-button" onClick={save}><Save/> SALVAR BUILD</button></div></div><div className="sensi-output">{[["GERAL",output.geral],["RED DOT",output.redDot],["ACOG / 2X",output.acog],["MIRA 4X",output.x4],["AWM",output.awm],["CÂMERA",output.camera]].map(([key,value])=><div className="sensi-stat" key={key}><span>{key}</span><strong>{value}</strong><div><i style={{width:`${Number(value)/2}%`}}/></div></div>)}</div><div className="analysis-grid"><article><Smartphone/><div><small>DPI IDEAL</small><strong>{dpiRec.text}</strong><span>Sampling alvo: {dpiRec.hz}</span></div></article><article><MonitorCog/><div><small>RESOLUÇÃO IDEAL</small><strong>{resolutionRec}</strong><span>Baseada em {input.fps} FPS e classe do processador</span></div></article><article><Gauge/><div><small>BOTÃO RECOMENDADO</small><strong>{output.fireButton}%</strong><span>{training?"Ajustado pela sua puxada real":"Estimativa inicial do hardware"}</span></div></article></div><div className="processor-row"><label>CLASSE DO PROCESSADOR<select value={cpu} onChange={e=>setCpu(e.target.value)}>{CPU_TIERS.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label>{output.factors.map(f=><span key={f.label}>{f.label}<b>{f.value}</b></span>)}</div></section>
    <section id="profiles" className="panel reactive-panel reveal"><SectionTitle icon={<BarChart3/>} kicker="CLOUD LOADOUTS" title="BUILDS DE ATLETA" text="Salve, compare e aplique suas calibrações competitivas."/><div className="profile-create"><input className="sx-input" maxLength={60} value={profileName} onChange={e=>setProfileName(e.target.value)} aria-label="Nome da build"/><button className="ui-button" onClick={save}><Save/> SALVAR</button><button className="ui-button ui-button-outline" onClick={exportCard}><Download/> CARD</button></div><div className="profile-grid">{profiles.length===0?<p className="empty-state">Nenhuma build salva.</p>:profiles.map(p=><article className="profile-card" key={p.id}><small>{new Date(p.created_at).toLocaleDateString("pt-BR")}</small><h3>{p.name}</h3><div className="profile-numbers"><span>GERAL <b>{p.data.geral??"—"}</b></span><span>RED DOT <b>{p.data.redDot??"—"}</b></span><span>BOTÃO <b>{p.data.fireButton??"—"}%</b></span></div><div className="profile-actions"><button onClick={()=>apply(p)}>APLICAR</button><button aria-label="Excluir build" onClick={async()=>{await deleteFn({data:{token:session.token,id:p.id}});await loadProfiles()}}><Trash2/></button></div></article>)}</div></section>
    <section className="training-protocol reveal"><div><p>ADAPTIVE COACH</p><h2>PROTOCOLO DE ESTABILIDADE</h2></div><article><Zap/><b>OVERFLICK</b><span>{training&&training.factor<.9?"Detectado: reduza 12% e aumente o botão.":"Faça 3 séries de 15 puxadas controladas."}</span></article><article><Crosshair/><b>HEAD CONTROL</b><span>Mantenha a retícula na cabeça por 180ms antes de soltar.</span></article><article><ShieldCheck/><b>FRAME PACING</b><span>Priorize FPS estável; picos prejudicam mais que resolução baixa.</span></article></section>
    <footer><div className="brand-mini"><Crosshair/> AIM LAB // HX</div><p>CALIBRAÇÃO COMPETITIVA — RESULTADOS VARIAM POR APARELHO E MECÂNICA</p><ShieldCheck/></footer>{toast&&<div className="toast"><Check/>{toast}</div>}
  </main>;
}

function SectionTitle({icon,kicker,title,text}:{icon:React.ReactNode;kicker:string;title:string;text?:string}){return <div className="section-title"><span className="section-icon">{icon}</span><div><p className="section-tag">{kicker}</p><h2>{title}</h2>{text&&<p>{text}</p>}</div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label>{label}{children}</label>}
function Range({label,value,min,max,step=1,unit,onChange}:{label:string;value:number;min:number;max:number;step?:number;unit:string;onChange:(v:number)=>void}){return <label>{label}<b>{value}{unit}</b><input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(+e.target.value)}/></label>}